App/Pages/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace App.Pages
{
    public class AddModel : PageModel
    {
        [BindProperty]
        public string Album { get; set; }

        [BindProperty]
        public DateTime Date { get; set; }

        [BindProperty]
        public string Artist { get; set; }

        [BindProperty]
        public string Title { get; set; }

        [BindProperty]
        public string[] Albums { get; set; }

        [BindProperty]
        public bool HasSelectedAlbum { get; set; } = false;

        private ISession Session;

        public void OnGet()
        {
            Session = HttpContext.Session;

            Console.WriteLine($"SESSION: {Session.GetString("IsArtist")}");
            if(Session.GetString("IsArtist") == null)
            {
                Response.Redirect("./Index");
            }

            Albums = MusicDataBase.GetAlbumsForArtist(Session.GetInt32("UserID"));
        }

        public IActionResult OnPostChooseAlbum(string albumButton)
        {
            if(ModelState.IsValid)
            {
                if(albumButton == null || albumButton == String.Empty) return RedirectToPage("./Add");

                Session = HttpContext.Session;
                Albums = MusicDataBase.GetAlbumsForArtist(Session.GetInt32("UserID"));

                if(IsAlbumValid(albumButton))
                {
                    HasSelectedAlbum = true;
                    Album = albumButton;
                    return Page();
                }

                return Page();
            }
            return RedirectToPage("./Error");
        }

        private bool IsAlbumValid(string albumButton)
        {
            foreach(var v in Albums)
            {
                if(v.Equals(albumButton))
                {
                    return true;
                }
            }

            return false;
        }

        public IActionResult OnPostAddSong()
        {
            if(ModelState.IsValid)
            {
                Session = HttpContext.Session;
                MusicDataBase.AddSong(Title, Album, Session.GetInt32("UserID"), Date.ToString("MM/dd/yyyy"));
                return RedirectToPage("./Add");
            }

            return RedirectToPage("./Error");
        }

        public IActionResult OnPostSendToAddAlbum()
        {
            if(ModelState.IsValid)
            {
                return RedirectToPage("./AddAlbum");
            }

            return RedirectToPage("./Error");
        }
    }
}

App/Pages/AddAlbum.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using App.Models;

namespace App.Pages
{
    public class AddAlbumModel : PageModel
    {
        [BindProperty]
        public string AlbumName { get; set; }
        [BindProperty]
        public DateTime ReleaseDate { get; set; }

        private ISession Session;

        public void OnGet()
        {
        }

        public IActionResult OnPostCreateAlbum(string addAlbumButton)
        {
            if(ModelState.IsValid)
            {
                Session = HttpContext.Session;

                Album[] albums = MusicDataBase.GetAlbumsFromArtistID((int) Session.GetInt32("UserID"));

                if(!IsDuplicate(albums))
                {

                    MusicDataBase.AddAlbum(AlbumName, Session.GetInt32("UserID"), ReleaseDate.ToString("MM/dd/yyyy"));
                    return RedirectToPage("./Add");
                }

                return Page();
            }

            return RedirectToPage("./Error");
        }

        private bool IsDuplicate(Album[] albums)
        {
            if(albums == null) return false;

            foreach(var v in albums)
            {
                if(v.AlbumTitle.Equals(AlbumName))
                {
                    return true;
                }
            }
            return false;
        }
    }
}

App/Pages/CreatePlaylist.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace App.Pages
{
    public class CreatePlaylistModel : PageModel
    {
        [BindProperty]
        public string PlaylistTitle { get; set; }

        private ISession Session;

        public void OnGet()
        {
            Session = HttpContext.Session;
            if(Session.GetString("IsLoggedIn") == null || Session.GetString("IsLoggedIn") == "FALSE")
            {
                Response.Redirect("./Index");
            }
        }

        public IActionResult OnPostCreatePlaylist()
        {
            if(ModelState.IsValid)
            {
                Session = HttpContext.Session;

                string[] playlists = MusicDataBase.GetPlaylistNamesForUserID((int) Session.GetInt32("UserID"));


                if(!IsDuplicate(playlists))
                {
                    MusicDataBase.CreatePlaylist((int) Session.GetInt32("UserID"), PlaylistTitle);
                    return RedirectToPage("./UserProfile");
                }

                return Page();
            }

            return RedirectToPage("./Error");
        }

        private bool IsDuplicate(string[] playlists)
        {
            if(playlists == null) return false;
            
            foreach(var v in playlists)
            {
                if(v.Equals(PlaylistTitle))
                {
                    return true;
                }
            }

            return false;
        }
    }
}

App/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace App.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

App/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace App.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string Password { get; set; }
        
        private ISession Session;

        public void OnGet()
        {
            Session = HttpContext.Session;
            if(Session.GetString("IsLoggedIn") == "TRUE")
            {
                Response.Redirect("./Index");
            }
        }

        public IActionResult OnPostLogin()
        {
            if(ModelState.IsValid)
            {
                Session = HttpContext.Session;

                if(MusicDataBase.UserExists(Email))
                {
                    if(!MusicDataBase.PasswordsMatch(Email, Password))
                    {
                        return Page();
                    }
                }
                
                Session.SetInt32("UserID", MusicDataBase.GetUserIDForEmail(Email));
                if(MusicDataBase.UserIsArtist(Session.GetInt32("UserID")))
                {
                    Session.SetString("IsArtist", "TRUE");
                }
                Session.SetString("SessionUser", MusicDataBase.GetUsernameForEmail(Email));
                Session.SetString("IsLoggedIn", "TRUE");
                return RedirectToPage("./Index");
            }

            return RedirectToPage("./Error");
        }
    }
}

App/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace App.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

App/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Http;

namespace App.Pages
{
    public class RegisterModel : PageModel
    {
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string Username { get; set; }

        // TODO: Minimum password length.
        [BindProperty]
        public string Password { get; set; }

        private ISession Session;

        public void OnGet()
        {
            Session = HttpContext.Session;
            if(Session.GetString("IsLoggedIn") == "TRUE")
            {
                Response.Redirect("./Index");
            }
        }

        public IActionResult OnPostRegister()
        {
            if(ModelState.IsValid)
            {
                Session = HttpContext.Session;
                if(!MusicDataBase.UserExists(Email))
                {
                    MusicDataBase.AddUser(Email, Username, Password);
                }
                else
                {
                    Session.SetString("IsRegistered", "TRUE");
                    Session.SetString("SessionUser", Username);
                    Session.SetString("IsArtist", "FALSE");

                    return RedirectToPage("./Login");
                }
                return RedirectToPage("./Index");
            }

            return RedirectToPage("./Error");
        }
    }
}

App/Pages/SearchSong.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using App.Models;

namespace App.Pages
{
    public class SearchSongModel : PageModel
    {

        [BindProperty]
        public Song[] Songs { get; private set; }

        [BindProperty]
        public List<string> ArtistNames { get; private set; }

        [BindProperty]
        public Album[] Albums { get; private set; }

        [BindProperty]
        public User[] Users { get; private set; }

        [BindProperty]
        public Playlist[] searchPlaylists {get; private set;}

        [BindProperty]
        public string[] CurrentUsersPlaylists { get; private set; }

        [BindProperty]
        public int PageUserID { get; private set; }

        [BindProperty]
        public string SearchString { get; set; }

        private ISession Session;

        public void OnPostSearch() 
        {
            SearchString = Request.Form["search-bar"];
            Session = HttpContext.Session;
            Session.SetString("SearchString", SearchString);
            GetData();
            if (Songs != null)
            {
                GetArtistData();
            }

            if(Session.GetString("IsLoggedIn") == "TRUE")
            {
                PageUserID = (int) Session.GetInt32("UserID");
                CurrentUsersPlaylists = MusicDataBase.GetPlaylistNamesForUserID(PageUserID);
            }
        }

        private void GetData() 
        {
            Session = HttpContext.Session;
            Albums = MusicDataBase.GetSearchResultsAlbum(Session.GetString("SearchString"));
            Users = MusicDataBase.GetSearchResultsUsers(Session.GetString("SearchString"));
            Songs = MusicDataBase.GetSearchResultsSong(Session.GetString("SearchString"));
            searchPlaylists = MusicDataBase.GetSearchResultsPlaylists(Session.GetString("SearchString"));
        }

        private void GetArtistData() 
        {
            ArtistNames = new List<string>();
            for (int i=0; i<Songs.Length; i++) 
                {
                    int artistId = MusicDataBase.FindArtistID(Songs[i].SongID);
                    string artistName = MusicDataBase.GetUserNameForID(artistId);
                    ArtistNames.Add(artistName);
                }
        }

        public IActionResult OnPostAdd() 
        {
            if(ModelState.IsValid)
            {
                Session = HttpContext.Session;
                SearchString = Session.GetString("SearchString");
                int songId = -1;
                GetData();
                string playlistName = Request.Form["add-song-button"];

                if ( IsPlaylist(playlistName) == false )
                    return Redirect("./SearchSong");
                
                try 
                {
                    songId = Convert.ToInt32(Request.Form["song-id"]);
                    if(IsSongID(songId) == false || songId < 0)
                    {
                        return Redirect("./SearchSong");
                    }
                } catch (InvalidCastException e)
                {
                    Console.WriteLine("Incorrect type of id" + e.Message);
                    return Redirect("./SearchSong");
                }

                Session = HttpContext.Session;
                PageUserID = (int) Session.GetInt32("UserID");

                int playlistId = MusicDataBase.GetPlaylistIDForPlaylistNameAndUserID(playlistName, PageUserID);
                MusicDataBase.AddSongToPlaylist(songId, playlistId);
                return Redirect("./SearchSong");
            }
            return RedirectToPage("./Error");
        }

        private bool IsPlaylist(string playlistName) 
        {
            Session = HttpContext.Session;
            PageUserID = (int) Session.GetInt32("UserID");
            CurrentUsersPlaylists = MusicDataBase.GetPlaylistNamesForUserID(PageUserID);

            foreach(var playlist in CurrentUsersPlaylists)
            {
                if( string.Equals(playlistName, playlist) )
                    return true;
            }

            return false;
        }

        private bool IsSongID(int songId)
        {
            foreach(var song in Songs)
            {
                if(song.SongID == songId)
                {
                    return true;
                }
            }

            return false;
        }

        public IActionResult OnPostViewPlaylist()
        {
            if(ModelState.IsValid)
            {
                Session = HttpContext.Session;
                Session.SetString("IsEditMode", "FALSE");
                //add checks
                int userIdToView = Convert.ToInt32(Request.Form["user-id"]);
                string viewPlaylist = Request.Form["view-playlist-button"];
                int playlistid = Convert.ToInt32(Request.Form["playlist-id"]);

                GetData();

                if(IsValidPlaylist(playlistid))
                {
                    return Redirect($"./ViewPlaylist?userId={userIdToView}&playlist={viewPlaylist}");
                }

                return Page();
            }
            return RedirectToPage("./Error");
        }

        private bool IsValidPlaylist(int playlistID)
        {
            foreach(var v in searchPlaylists)
            {
                if(v.PlaylistId == playlistID)
                {
                    return true;
                }
            }
            return false;
        }

        public IActionResult OnPostViewProfile()
        {
            if(ModelState.IsValid)
            {
                Session = HttpContext.Session;
                Session.SetString("IsEditMode", "FALSE");
                //add checks
                int userIdToView = Convert.ToInt32(Request.Form["user-id"]);

                return Redirect($"./UserProfile?userId={userIdToView}");
            }
            return RedirectToPage("./Error");
        }


        public bool isValidUserId(int userId)
        {
            return false;
        }

        public IActionResult OnPostViewSelectedAlbum()
        {
            int albumTitle = Convert.ToInt32(Request.Form["album-id"]);

            if(ModelState.IsValid)
            {
                GetData();

                if(IsValidAlbum(albumTitle))
                {
                    return Redirect($"./ViewAlbum?album={albumTitle}&albumId={Request.Form["album-id"]}");
                }

                return Page();
            }

            return RedirectToPage("./Error");
        }

        private bool IsValidAlbum(int albumid)
        {
            Session = HttpContext.Session;
            foreach(var v in Albums)
            {
                if(v.AlbumID == albumid)
                {
                    Session.SetString("ArtistName", v.ArtistName);
                    return true;
                }
            }

            return false;
        }

        public bool isValidPlaylistForUserId(int userId, string playlistName){
            return false;
        }
    }
}

App/Pages/Add.cshtml
@page
@model App.Pages.AddModel
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor


@{

    var hasSelect = Model.HasSelectedAlbum;
    var artist = @HttpContextAccessor.HttpContext.Session.GetString("SessionUser");
}


<section id = "main">
    <div class="left-floating-div text-light" id="add-song-div">
        <u>
            <h1>Add</h1>
        </u>
        @using (Html.BeginForm("OnPostSubmitButton", "AddSongModel", FormMethod.Post))
        {
            @if(!hasSelect)
            {
                @if(Model.Albums != null)
                {
                    <h3>Albums you own: </h3>
                    @foreach(var album in Model.Albums)
                    {
                        <input class="mm_button" type="submit" name="albumButton" id="albumButton" asp-page-handler="ChooseAlbum" value=@album />
                    }
                }
                <input class="mm_button" type="submit" name="addAlbumButton" id="addAlbumButton" asp-page-handler="SendToAddAlbum" value="Create" />
            }
            else
            {
                <div>
                    <h1>@Model.Album</h1>
                    @Html.TextBoxFor(Model => Model.Title, new { @type = "text", @placeholder = "Title", @class = "mm_text", @required="required"})
                    @Html.TextBoxFor(Model => Model.Album, new { @type = "text",  @class = "mm_text", @placeholder=@Model.Album, @readonly="readonly" })
                    @Html.TextBoxFor(Model => Model.Artist, new { @type = "text",  @class = "mm_text", @placeholder=@artist, @readonly="readonly" })
                    @Html.EditorFor(Model => Model.Date, new { @type = "date"})
                    <input class="mm_button" type="submit" asp-page-handler="AddSong" value="Submit"/>
                </div>
            }

            <div></div>
        }
    </div>
</section>

App/Pages/AddAlbum.cshtml
@page
@model App.Pages.AddAlbumModel
@{
}

<section id = "main">
    <div class="left-floating-div text-light" id="add-song-div">
        <u>
            <h1>Add</h1>
        </u>
        @using (Html.BeginForm("OnPostSubmitButton", "AddSongModel", FormMethod.Post))
        {
            <div>
                @Html.Label("Enter an album to create!")
                @Html.TextBoxFor(Model => Model.AlbumName, new { @type = "text", @placeholder = "Title", @class = "mm_text", @required="required"})
                @Html.TextBoxFor(Model => Model.ReleaseDate, new { @type = "date", @class = "mm_text", @required="required"})
                <input class="mm_button" type="submit" asp-page-handler="CreateAlbum" value="Create"/>
            </div>
        }
    </div>
</section>

App/Pages/CreatePlaylist.cshtml
@page
@model App.Pages.CreatePlaylistModel
@{
}

<section id="main">
    <div class="left-floating-div text-light" id="add-playlist-div">
        <u>
            <h1>Create Playlist</h1>
        </u>
        @using (Html.BeginForm("OnPostSubmitButton", "CreatePlaylistModel", FormMethod.Post))
        {
            <div>
                @Html.Label("Enter a playlist title to create!")
                @Html.TextBoxFor(Model => Model.PlaylistTitle, new { @type = "text", @class="mm_text", @required="required", @placeholder="Title"})
                <input class="mm_button" type="submit" asp-page-handler="CreatePlaylist" value="Create"/>
            </div>
        }
    </div>
</section>

App/Pages/Login.cshtml
@page
@model App.Pages.LoginModel
@{
}

<section id="main">
    <div class="left-floating-div text-light">
        <u>
            <h1>Login</h1>
        </u>
        @using (Html.BeginForm("Login", "AccountHandler", FormMethod.Post))
        {
            <div>
                @Html.LabelFor(Model => Model.Email, "Email")
            </div>
            <div>
                @Html.TextBoxFor(Model => Model.Email, new { @type="email", @class="mm_text", @required="required"})
            </div>

            <div>
                @Html.LabelFor(Model => Model.Password, "Password")
            </div>
            <div>
                @Html.PasswordFor(Model => Model.Password, new { @type="password", @class="mm_text", @required="required"})
            </div>

            <input class="mm_button" type="submit" asp-page-handler="Login" value="Login"/>
        }
    </div>
</section>


App/Pages/Register.cshtml
@page
@model App.Pages.RegisterModel
@{
}


<section id="main">
    <div class="left-floating-div text-light">
        <u>
            <h1>Register</h1>
        </u>
        @using (Html.BeginForm("Register", "AccountHandler", FormMethod.Post))
        {
            <div>
                @Html.LabelFor(Model => Model.Email, "Email")
            </div>
            <div>
                @Html.TextBoxFor(Model => Model.Email, new { @type="email", @class="mm_text", @required="required"})
            </div>

            <div>
                @Html.LabelFor(Model => Model.Username, "Username")
            </div>
            <div>
                @Html.TextBoxFor(Model => Model.Username, new { @type="text", @class="mm_text", @required="required"})
            </div>

            <div>
                @Html.LabelFor(Model => Model.Password, "Password")
            </div>
            <div>
                @Html.PasswordFor(Model => Model.Password, new { @type="password", @class="mm_text", @required="required"})
            </div>

            <input class="mm_button" type="submit" asp-page-handler="Register" value="Register"/>
        }
    </div>
</section>

App/Pages/RegisterArtist.cshtml
@page
@model App.Pages.RegisterArtistModel
@{
}

<section id="main">
    <div class="left-floating-div text-light">
        <u>
            <h1>Become an Artist!</h1>
        </u>
        @using (Html.BeginForm("BecomeArtist", "AccountHandler", FormMethod.Post))
        {
            <div>
                @Html.LabelFor(Model => Model.Email, "Enter Email to become an artist!")
            </div>
            <div>
                @Html.TextBoxFor(Model => Model.Email, new { @type="text", @class="mm_text", @required="required"})
            </div>

            <input class="mm_button" type="submit" asp-page-handler="Register" value="Register"/>
        }
    </div>
</section>

App/Pages/SearchSong.cshtml
@page
@model App.Pages.SearchSongModel
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    var SessionUserID = @HttpContextAccessor.HttpContext.Session.GetInt32("UserID");
}

<section id="main">

    <div class="text-center text-light">
        <h1 class="display-4 text-light">Search</h1>
            @using (Html.BeginForm("SearchEverything", "Search", FormMethod.Post)) 
            {
                @if (Model.SearchString != null){
                    <input type="text" id="searchBar" class="search-bar" name="search-bar" value=@Model.SearchString autocomplete="off"/>
                } else {
                    <input type="text" id="searchBar" class="search-bar" name="search-bar" placeholder="Search..." autocomplete="off"/>
                }
                <input class="mm_button" type="submit" asp-page-handler="Search" value="Search"/>
            }


        <p class="text-light" name="content" id="content"></p>

            @if(Model.Songs != null && Model.ArtistNames != null)
            {
                <h2 class="display-4 text-light">Songs</h2>
                @for(int i = 0; i < Model.Songs.Length; i++)
                {
                    @if(@HttpContextAccessor.HttpContext.Session.GetString("IsLoggedIn") == "TRUE")
                    {
                        @using(Html.BeginForm("OnPostAddSongPress", "AddSong", FormMethod.Post))
                        {
                            <div class="song-container">
                                <textarea id="song-id" name="song-id" hidden="hidden">@Model.Songs[i].SongID</textarea>
                                <div class="search-song-container-subsection" name="song-title">
                                    @Model.Songs[i].Title
                                </div>
                                <div class="search-song-container-subsection" name="song-album">
                                    @Model.Songs[i].AlbumName
                                </div>
                                <div class="search-song-container-subsection" name="song-artist">
                                    @Model.ArtistNames[i]
                                </div>
                                <div class="search-song-container-subsection" name="release-date">
                                    @Model.Songs[i].ReleaseDate
                                </div>
                                <div>
                                    <div class="dropdown">
                                        <button class="dropdown-button">Add to Playlist</button>
                                        <div class="dropdown-content text-light">
                                            @if (Model.CurrentUsersPlaylists != null) 
                                            {
                                                @foreach(var playlist in Model.CurrentUsersPlaylists)
                                                {
                                                    <input class="mm_button" type="submit" id="add-song-button" name="add-song-button" asp-page-handler="Add" value=@playlist />
                                                }
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div class="song-container">
                            <textarea id="song-id" name="song-id" hidden="hidden">@Model.Songs[i].SongID</textarea>
                            <div class="song-contianer-subsection" name="song-title">
                                @Model.Songs[i].Title
                            </div>
                            <div class="song-contianer-subsection" name="song-album">
                                @Model.Songs[i].AlbumName
                            </div>
                            <div class="song-contianer-subsection" name="song-artist">
                                @Model.ArtistNames[i]
                            </div>
                            <div class="song-contianer-subsection" name="release-date">
                                @Model.Songs[i].ReleaseDate
                            </div>
                        </div>
                    }
                }
            }

            <!-- Playlists -->

            @if(Model.searchPlaylists != null)
            {
                <h2 class="display-4 text-light">Playlists</h2>
                @foreach(var playlist in Model.searchPlaylists)
                {
                    @using(Html.BeginForm("OnPostViewPlaylist", "ViewPlaylist", FormMethod.Post))
                    {
                        <textarea hidden="hidden" id="playlist-id">@playlist.PlaylistId</textarea>
                        <div class="listing-container">
                            <textarea id="user-id" name="user-id" hidden="hidden">@playlist.UserId</textarea>
                            <div class="playlist-name">
                                <input class="mm_button" type="submit" id="view-playlist-button" name="view-playlist-button" asp-page-handler="ViewPlaylist" value=@playlist.PlaylistTitle />
                            </div>
                        </div>
                    }
                }
            }

            <!-- Albums -->

            @if(Model.Albums != null)
            {
                <h2 class="display-4 text-light">Albums</h2>
                @foreach(var album in Model.Albums)
                {
                    @using(Html.BeginForm("OnPostViewSelectedAlbum", "SearchSongModel", FormMethod.Post))
                    {
                        <div class="listing-container">
                            <textarea id="album-id" name="album-id" hidden="hidden">@album.AlbumID</textarea>
                            <div class="album-name">
                                <input class="mm_button" type="submit" id="view-album-button" name="view-album-button" asp-page-handler="ViewSelectedAlbum" value=@album.AlbumTitle />
                            </div>
                        </div>
                    }
                }
            }

            <!-- Users -->

            @if(Model.Users != null)
            {
                <h2 class="display-4 text-light">Users</h2>
                @foreach(var user in Model.Users)
                {
                    @using(Html.BeginForm("OnPostViewProfile", "ViewProfile", FormMethod.Post))
                    {
                        <div class="listing-container">
                            <textarea id="user-id" name="user-id" hidden="hidden">@user.UserID</textarea>
                            <div class="username">
                                <input class="mm_button" type="submit" id="view-profile-button" name="view-profile-button" asp-page-handler="ViewProfile" value=@user.Username />
                            </div>
                        </div>
                    }
                }
            }

            <!-- Playlists -->



            <!-- Do same as above for album and playlist (May need to create playlist model object and album model object to get id) -->

        </div>
</section>